AllCops:
  DisplayCopNames: true

LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
